services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
      - "8787:8787"
    volumes:
      - "./realm-data:/opt/keycloak/data/import"
    command:
      - start-dev --import-realm