services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_PROXY: 'edge'
      KC_HTTP_PORT: 8080
      KC_HOSTNAME: 'keycloak'
    ports:
      - "8080:8080"
      - "8787:8787"
    volumes:
      - "./realm-data:/opt/keycloak/data/import"
    command:
      - start-dev --import-realm
  user_profile:
    image: hungdhvn/authn-service:0.0.3
    environment:
      AUTH_SERVICE_URL: http://keycloak:8080/realms/vietcombank_ad_onboarding/protocol/openid-connect/
    ports:
      - "8000:8000"