server:
  port: 8000
  servlet:
    context-path: /authen-service
springdoc:
  swagger-ui:
  packagesToScan: vietcombank
logging:
  level:
    #    root: DEBUG
    com.vietcombank: DEBUG
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG